### ISSUE TITLE
Issue Capstone

### ISSUE THREAD

**Issue by jasonfelice** [mavericks-db/capstone01#3]
**The webpage is neat and everything looks clean. Good job with the design and mobile responsiveness :+1:**
However please refer to the following issues:

- [ ] Please fix the white space on the right side. It occurs on the tablet view.
- [ ] Kindly consider adding transitions and animations to the nav links to create a better user experience.
- [ ] Make sure the cards under the main section do not move on hover. Can be fixed by giving them a default border.
- [ ] Consider adding a WebKit textbox background image to the headline text. [OPTIONAL]

**Comment by mavericksbalitaan** [comment]
Thanks for the comments. 👍 
Done implementing the changes here a0ad09f87434857609a96501b9183d0e26278eee
